name: Deploy to Hetzner

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Deploy to Hetzner
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HETZNER_HOST }}
          username: ${{ secrets.HETZNER_USERNAME }}
          key: ${{ secrets.HETZNER_SSH_KEY }}
          script: |
            cd ${{ secrets.PROJECT_PATH }}
            git pull origin master

            # Debug check
            echo "Checking bootstrap/cache directory..."
            ls -la bootstrap/cache/

            echo "Force remove with sudo if needed"
            sudo rm -f bootstrap/cache/*.php

            echo "Verifying removal..."
            ls -la bootstrap/cache/

            composer install --no-dev --optimize-autoloader
            npm install
            npm run build

            php artisan optimize:clear
            php artisan migrate --force
            php artisan config:cache
            php artisan view:cache
            php artisan event:cache

            echo "🚀 Application deployed!"
