name: Deploy to Hetzner

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Deploy to Hetzner
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HETZNER_HOST }}
          username: ${{ secrets.HETZNER_USERNAME }}
          key: ${{ secrets.HETZNER_SSH_KEY }}
          script: |
            cd ${{ secrets.PROJECT_PATH }}
            git pull origin master

            php artisan optimize:clear
            rm -f bootstrap/cache/*.php

            composer install --no-dev --optimize-autoloader
            npm install
            npm run build

            php artisan migrate --force

            php artisan optimize
            php artisan event:cache

            echo "🚀 Application deployed!"
